version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: glasses_db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_db/init_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  crawl:
    build:
      context: .
      dockerfile: crawl_data/Dockerfile
    depends_on:
      - mysql_db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: glasses_db
    ports:
      - "8001:8001"

  api:
    build:
      context: .
      dockerfile: mysql_api/Dockerfile
    depends_on:
      - mysql_db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: glasses_db
    ports:
      - "8000:8000"

  ui:
    build:
      context: ./app_main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    depends_on:
      - mysql_db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=glasses_db

volumes:
  mysql_data:
